# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVModel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='url',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='programdetail',
            name='address',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='type',
            name='url',
            field=models.CharField(max_length=500),
        ),
    ]
