# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TVModel', '0003_programdetail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programdetail',
            name='menu',
            field=models.CharField(max_length=15000),
        ),
    ]
